### ISSUE TITLE
Add stress test feature

### ISSUE THREAD

**Issue by svenska-primekey** [Keyfactor/ejbca-easy-rest-client#38]
**Is your feature request related to a problem or specific use case? Please describe.**
There should be an option to stress test enrollments with this utility. This utility is more modern than the Client Toolbox Rest test and this tool should be extended to support stress testing.

**Describe the solution you'd like**
Stress test with options:
Use a unique key for each request
Provide a directory with keys already generated for stress testing, then create CSR
Provide a subject DN to comply with EEP DN
Provide SAN to comply with EEP SAN's
Provide key type for test (ECDSA, RSA, PQC, Hybrid)

**Describe alternatives you've considered**
Find a new product

**Product deployment**
Please complete the following information:
 - Deployment format: software or container
 - Version: ASAP

**Additional context**
EJBCA needs better tooling to stress test the REST API.

**Comment by primetomas** [comment]
Currently we do have the REST stress test command in clientToolBox.
./ejbcaClientToolBox.sh RESTTest

I agree that it would be a nice addition to the easy-rest-client though.
